## Accuracy Assessment Stats and Confusion Matrices for S2 Tile 16QDH, 2019-05-07

In [1]:
import os
import pandas as pd
import geopandas as gpd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [2]:
sargassum_aa_gdf = gpd.read_file('/Users/arbailey/natcap/idb/data/work/sargassum/ip/aapointsV2_16QDH_20190507_validated.shp')
sargassum_aa_gdf = sargassum_aa_gdf.dropna()  # remove rows w/null
sargassum_aa_gdf

subSWIR  lowcorr  subNoSWIR  class_mask  ndvidiff  allbands  lowcorrB8  \
0          1        1          1           0         1         1          1   
1          1        1          1           0         1         1          1   
2          1        1          1           0         1         1          1   
3          1        1          1           0         1         1          1   
4          1        1          1           0         1         1          1   
..       ...      ...        ...         ...       ...       ...        ...   
395        0        0          0           0         0         0          0   
396        0        0          0           0         0         0          0   
397        0        0          0           0         0         0          0   
398        0        0          0           0         0         0          0   
399        0        0          0           0         0         0          0   

     sarg_count  validclass  classdesc  sarg_pa  \
0             6         0.0  sargassum      1.0   
1             6         0.0  sargassum      1.0   
2             6         0.0  sargassum      1.0   
3             6         0.0  sargassum      1.0   
4             6         0.0  sargassum      1.0   
..          ...         ...        ...      ...   
395           0         5.0      water      0.0   
396           0         5.0      water      0.0   
397           0         5.0      water      0.0   
398           0         5.0      water      0.0   
399           0         5.0      water      0.0   

                           geometry  
0    POINT (509665.000 2249615.000)  
1    POINT (486545.000 2274925.000)  
2    POINT (485445.000 2273915.000)  
3    POINT (485455.000 2273885.000)  
4    POINT (485335.000 2273875.000)  
..                              ...  
395  POINT (497445.000 2219445.000)  
396  POINT (505555.000 2223295.000)  
397  POINT (508195.000 2222635.000)  
398  POINT (501515.000 2222455.000)  
399  POINT (499565.000 2221075.000)  

[391 rows x 12 columns]

In [3]:
print(confusion_matrix(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['lowcorr']))
print(classification_report(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['lowcorr'], labels=[0, 1]))
print(accuracy_score(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['lowcorr']))

[[208  25]
 [  1 157]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94       233
           1       0.86      0.99      0.92       158

    accuracy                           0.93       391
   macro avg       0.93      0.94      0.93       391
weighted avg       0.94      0.93      0.93       391

0.9335038363171355


In [4]:
print(confusion_matrix(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['ndvidiff']))
print(classification_report(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['ndvidiff'], labels=[0, 1]))
print(accuracy_score(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['ndvidiff']))

[[218  15]
 [  4 154]]
              precision    recall  f1-score   support

           0       0.98      0.94      0.96       233
           1       0.91      0.97      0.94       158

    accuracy                           0.95       391
   macro avg       0.95      0.96      0.95       391
weighted avg       0.95      0.95      0.95       391

0.9514066496163683


In [5]:
print(confusion_matrix(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['lowcorrB8']))
print(classification_report(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['lowcorrB8'], labels=[0, 1]))
print(accuracy_score(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['lowcorrB8']))

[[200  33]
 [  0 158]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92       233
           1       0.83      1.00      0.91       158

    accuracy                           0.92       391
   macro avg       0.91      0.93      0.91       391
weighted avg       0.93      0.92      0.92       391

0.9156010230179028


In [6]:
print(confusion_matrix(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['subSWIR']))
print(classification_report(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['subSWIR'], labels=[0, 1]))
print(accuracy_score(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['subSWIR']))

[[210  23]
 [  6 152]]
              precision    recall  f1-score   support

           0       0.97      0.90      0.94       233
           1       0.87      0.96      0.91       158

    accuracy                           0.93       391
   macro avg       0.92      0.93      0.92       391
weighted avg       0.93      0.93      0.93       391

0.9258312020460358


In [7]:
print(confusion_matrix(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['subNoSWIR']))
print(classification_report(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['subNoSWIR'], labels=[0, 1]))
print(accuracy_score(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['subNoSWIR']))

[[213  20]
 [ 21 137]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       233
           1       0.87      0.87      0.87       158

    accuracy                           0.90       391
   macro avg       0.89      0.89      0.89       391
weighted avg       0.90      0.90      0.90       391

0.8951406649616368


In [8]:
print(confusion_matrix(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['allbands']))
print(classification_report(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['allbands'], labels=[0, 1]))
print(accuracy_score(sargassum_aa_gdf['sarg_pa'], sargassum_aa_gdf['allbands']))

[[216  17]
 [  8 150]]
              precision    recall  f1-score   support

           0       0.96      0.93      0.95       233
           1       0.90      0.95      0.92       158

    accuracy                           0.94       391
   macro avg       0.93      0.94      0.93       391
weighted avg       0.94      0.94      0.94       391

0.9360613810741688


In [9]:
sargassum_aa_gdf.groupby(['sarg_count','validclass','classdesc','sarg_pa']).count()
# .agg(['count'])

subSWIR  lowcorr  subNoSWIR  \
sarg_count validclass classdesc sarg_pa                                
0          1.0        other veg 0.0          131      131        131   
           3.0        buildings 0.0            2        2          2   
           4.0        clouds    0.0           13       13         13   
           5.0        water     0.0           54       54         54   
1          1.0        other veg 0.0            4        4          4   
           2.0        beach     0.0            2        2          2   
           4.0        clouds    0.0            1        1          1   
2          0.0        sargassum 1.0            1        1          1   
           1.0        other veg 0.0            2        2          2   
3          0.0        sargassum 1.0            3        3          3   
           1.0        other veg 0.0            1        1          1   
           4.0        clouds    0.0            1        1          1   
4          0.0        sargassum 1.0            8        8          8   
           1.0        other veg 0.0            5        5          5   
5          0.0        sargassum 1.0           11       11         11   
           1.0        other veg 0.0            5        5          5   
           4.0        clouds    0.0            1        1          1   
6          0.0        sargassum 1.0          135      135        135   
           1.0        other veg 0.0            8        8          8   
           4.0        clouds    0.0            3        3          3   

                                         class_mask  ndvidiff  allbands  \
sarg_count validclass classdesc sarg_pa                                   
0          1.0        other veg 0.0             131       131       131   
           3.0        buildings 0.0               2         2         2   
           4.0        clouds    0.0              13        13        13   
           5.0        water     0.0              54        54        54   
1          1.0        other veg 0.0               4         4         4   
           2.0        beach     0.0               2         2         2   
           4.0        clouds    0.0               1         1         1   
2          0.0        sargassum 1.0               1         1         1   
           1.0        other veg 0.0               2         2         2   
3          0.0        sargassum 1.0               3         3         3   
           1.0        other veg 0.0               1         1         1   
           4.0        clouds    0.0               1         1         1   
4          0.0        sargassum 1.0               8         8         8   
           1.0        other veg 0.0               5         5         5   
5          0.0        sargassum 1.0              11        11        11   
           1.0        other veg 0.0               5         5         5   
           4.0        clouds    0.0               1         1         1   
6          0.0        sargassum 1.0             135       135       135   
           1.0        other veg 0.0               8         8         8   
           4.0        clouds    0.0               3         3         3   

                                         lowcorrB8  geometry  
sarg_count validclass classdesc sarg_pa                       
0          1.0        other veg 0.0            131       131  
           3.0        buildings 0.0              2         2  
           4.0        clouds    0.0             13        13  
           5.0        water     0.0             54        54  
1          1.0        other veg 0.0              4         4  
           2.0        beach     0.0              2         2  
           4.0        clouds    0.0              1         1  
2          0.0        sargassum 1.0              1         1  
           1.0        other veg 0.0              2         2  
3          0.0        sargassum 1.0              3         3  
           1.0        other veg 0.0              