In [1]:
import os
import h5py
import numpy as np
import pandas as pd
import geopandas as gp

### Exploration of HDF file. After https://lpdaac.usgs.gov/resources/e-learning/getting-started-gedi-l1b-data-python/

In [3]:
inDir = '/Users/arbailey/natcap/idb/data/source/nasa_blackmarble'  
h5_files = [f for f in os.listdir(inDir) if f.startswith('VNP46A2') and f.endswith('.h5')]
h5_files

['VNP46A2.A2015152.h09v06.001.2020238152007.h5',
 'VNP46A2.A2013152.h09v07.001.2020148021019.h5',
 'VNP46A2.A2016153.h09v07.001.2020267134228.h5',
 'VNP46A2.A2015152.h09v07.001.2020238085217.h5',
 'VNP46A2.A2019152.h09v07.001.2021025140656.h5',
 'VNP46A2.A2013152.h09v06.001.2020147222645.h5',
 'VNP46A2.A2012153.h09v07.001.2020062021316.h5',
 'VNP46A2.A2014152.h09v07.001.2020199084347.h5',
 'VNP46A2.A2018152.h09v06.001.2020342121256.h5',
 'VNP46A2.A2016153.h09v06.001.2020267141826.h5',
 'VNP46A2.A2014152.h09v06.001.2020199104312.h5',
 'VNP46A2.A2019152.h09v06.001.2021025141919.h5',
 'VNP46A2.A2018152.h09v07.001.2020342122140.h5',
 'VNP46A2.A2017152.h09v06.001.2020293023218.h5',
 'VNP46A2.A2017152.h09v07.001.2020293023034.h5',
 'VNP46A2.A2012153.h09v06.001.2020060065147.h5']

In [5]:
test_filepath = os.path.join(inDir,h5_files[0])
testfile = h5py.File(test_filepath,'r')
list(testfile.keys()) 

['HDFEOS', 'HDFEOS INFORMATION']

In [7]:
list(testfile['HDFEOS']) 

['ADDITIONAL', 'GRIDS']

In [8]:
list(testfile['HDFEOS INFORMATION']) 

['StructMetadata.0']

In [10]:
list(testfile['HDFEOS']['ADDITIONAL']) 

['FILE_ATTRIBUTES']

In [12]:
list(testfile['HDFEOS']['GRIDS']) 

['VNP_Grid_DNB']

In [11]:
list(testfile['HDFEOS']['ADDITIONAL']['FILE_ATTRIBUTES']) 

[]

In [13]:
list(testfile['HDFEOS']['GRIDS']['VNP_Grid_DNB']) 

['Data Fields']

In [19]:
list(testfile['HDFEOS']['GRIDS']['VNP_Grid_DNB']['Data Fields']) 

['DNB_BRDF-Corrected_NTL',
 'DNB_Lunar_Irradiance',
 'Gap_Filled_DNB_BRDF-Corrected_NTL',
 'Latest_High_Quality_Retrieval',
 'Mandatory_Quality_Flag',
 'QF_Cloud_Mask',
 'Snow_Flag']

In [21]:
list(testfile['HDFEOS']['GRIDS']['VNP_Grid_DNB']['Data Fields'])

['DNB_BRDF-Corrected_NTL',
 'DNB_Lunar_Irradiance',
 'Gap_Filled_DNB_BRDF-Corrected_NTL',
 'Latest_High_Quality_Retrieval',
 'Mandatory_Quality_Flag',
 'QF_Cloud_Mask',
 'Snow_Flag']

In [22]:
list(testfile['HDFEOS']['GRIDS']['VNP_Grid_DNB']['Data Fields']['Gap_Filled_DNB_BRDF-Corrected_NTL'])

[array([  621,   986,   169, ..., 65535, 65535, 65535], dtype=uint16),
 array([  137,    91,    68, ..., 65535, 65535, 65535], dtype=uint16),
 array([   66,    51,    58, ..., 65535, 65535, 65535], dtype=uint16),
 array([   77,    58,    57, ..., 65535, 65535, 65535], dtype=uint16),
 array([  178,   153,    93, ..., 65535, 65535, 65535], dtype=uint16),
 array([  198,   123,    94, ..., 65535, 65535, 65535], dtype=uint16),
 array([  220,   229,   179, ..., 65535, 65535, 65535], dtype=uint16),
 array([  260,   239,   247, ..., 65535, 65535, 65535], dtype=uint16),
 array([  344,   302,   246, ..., 65535, 65535, 65535], dtype=uint16),
 array([  461,   371,   312, ..., 65535, 65535, 65535], dtype=uint16),
 array([  464,   424,   463, ..., 65535, 65535, 65535], dtype=uint16),
 array([  363,   394,   606, ..., 65535, 65535, 65535], dtype=uint16),
 array([  411,   390,   440, ..., 65535, 65535, 65535], dtype=uint16),
 array([  334,   361,   345, ..., 65535, 65535, 65535], dtype=uint16),
 array